// Sensors
#define ENTRANCE_SENSOR_TRIGGER_PIN 32
#define DOOR_SENSOR_TRIGGER_PIN 33
#define ENTRANCE_SENSOR_ECHO_PIN 34
#define DOOR_SENSOR_ECHO_PIN 35
#define PHOTORESISTOR_PIN 39
#define KEYPAD_ROW_1_PIN 13
#define KEYPAD_ROW_2_PIN 12
#define KEYPAD_ROW_3_PIN 14
#define KEYPAD_ROW_4_PIN 27
#define KEYPAD_COLUMN_1_PIN 17
#define KEYPAD_COLUMN_2_PIN 16
#define KEYPAD_COLUMN_3_PIN 4
#define BUTTON_PIN 36

// Actuators
#define SERVO_PIN 26
#define BUZZER_PIN 2
#define RELAY_PIN 25
#define LCD_ADDRESS 0x27
#define LCD_ROWS 2
#define LCD_COLUMNS 16