// ESTADOS
#define ESTADO_CERRADURA_INIT 50
#define ESTADO_BLOQUEADO_ESPERANDO_VISITA 100
#define ESTADO_ESPERANDO_INGRESO_CONTRASENA 200
#define ESTADO_VALIDACION_CLAVE 300
#define ESTADO_ESPERANDO_APERTURA_PUERTA 400
#define ESTADO_ESPERANDO_CIERRE_PUERTA 500
#define ESTADO_ESPERANDO_ENTRADA_PERSONA 600